version: '3'
services:
  dbase:
    image: mysql:8.0.23
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports: 
    - 33062:3306
  # The Application
  app:
    build:
      context: ./docker/php-fpm
    user: "1000"
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    links:
      - dbase
  node:
    image: node:12-alpine3.9
#    build:
#      context: ./docker/node
    #comando da lanciare docker-compose run --rm node sh -> da sh yarn install / watch / encore dev
    container_name: node-service
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
  web:
    build:
      context: ./docker/nginx
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    links:
      - app
    ports:
      - 8110:80
volumes:
  mysql-data:
